name: Docker build and push

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: show values
      run: |
        echo ${{ env.DOCKER_USERNAME }}
        echo ${{ env.DOCKER_SECRET }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_SECRET }}
    
    - name: Build and push Docker image
      run: |
        sh build_container.sh